FROM python:3.7.5

## To create the image on Cloud Build: 
## gcloud builds submit --tag gcr.io/hackensack-tyco/python

# Pandas to import CSV files as dataframe, statistics for Fisher test, dataframe manipulation,  statistics (multiple testing), and JSON manipulation
RUN pip install numpy pandas scipy statsmodels ndjson


CMD ["date"]
