FROM python:3

## To create the image on Cloud Build: 
## gcloud builds submit --tag gcr.io/hackensack-tyco/python

# Pandas to import CSV files as dataframe
RUN pip install pandas

# Statistics module for Python
RUN pip install scipy

CMD ["date"]
